version: 2.1

jobs:
  say-hello:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout
      - run:
          name: ""
          command: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
      - run:
          name: "Création de l'image"
          command: "docker build -t nave145/node-js-sample ."
      - run:
          name: "Exécution du script"
          command: "docker run -d -p 8080:8080 --name conteneur_test nave145/node-js-sample"
      - run:
          name: "Vérification du conteneur"
          command: "curl localhost:8080"
      - run:
          name: "Push de l'image"
          command: "docker push nave145/node-js-sample"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello