version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    machine: # executor type
      image: ubuntu-2204:current

    steps:
      - checkout
      - run:
          name: "Création de l'image"
          command: "docker build -t inane-inaccompli/node-js-sample ."
      - run:
          name: "Exécution du script"
          command: "docker run -d -p 8080:8080 --name conteneur_test inane-inaccompli/node-js-sample"
      - run:
          name: "Vérification du conteneur"
          command: "curl localhost:8080"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello